### ISSUE TITLE
How does this part work

### ISSUE THREAD

**Issue by pkieltyka** [didierfranc/react-waterfall-example#4]
Hi @didierfranc - nice work on this library, I dig it.

Im reading the source and trying to understand how this line works to set the `user` object on the state: https://github.com/didierfranc/react-waterfall-example/blob/master/src/App.js#L38

its just calling the action, and the action returns a new object, but where does it `this.setState({ .. })`

**Comment by pkieltyka** [comment]
nice library, but try to keep things as explicit as possible, I believe actions somehow calls this.setState().. im not sure how it gets the right "this", and its not clear from the line `actions.getUser()` in componentDidMount() this is happening either

**Comment by didierfranc** [comment]
Did you read that ? https://medium.freecodecamp.org/replacing-redux-with-the-new-react-context-api-8f5d01a00e8c

getUser is just right here https://github.com/didierfranc/react-waterfall-example/blob/master/src/store.js#L11-L17

and an action is just `state => stateChunk`
