### ISSUE TITLE
Your vscode theme is ???

### ISSUE THREAD

**Issue by yeyuguo** [didierfranc/react-waterfall-example#6]
Hello, I want to know, what is your vscode color matching theme? Can you give me a configuration?

**Comment by yeyuguo** [comment]
![image](https://note.youdao.com/yws/public/resource/bf88a0b781b58e500d33fc38530caf1b/xmlnote/DC67E1AB09B1407CA6CF861EC2266B33/37946)
 like this

**Comment by didierfranc** [comment]
https://medium.com/p/my-setup-7367b261894d

**Comment by yeyuguo** [comment]
thank you very much
